# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4060b0d17ec830b0a41426d292585930b6b7ef308ef2454953086c3c5052cb935bdd6d5593b3d55c3ffd63a6e7e960cc8765b6b4b95485261307bcbf8109eb0a

test:
  secret_key_base: a9c4ec88c9436a35f4cf083c29a843127ec303c47b6e842a19fda0878ba8a7ac4f544605e179b7a9508525bf035af380e792a4de4ec15193b51866f519b1a38c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
